### ISSUE TITLE
회원 탈퇴 기능 추가

### ISSUE THREAD

**Issue by IDKNWHORU** [Ludium-Official/ludium-world#1]
정보 보호법 준수

**Comment by IDKNWHORU** [comment]
회원 탈퇴 정책을 결정한 후 진행해야 될듯함.

- 게시글 보존 여부(댓글 등 회원 정보와 연관된 모든 데이터 포함)
- 회원 탈퇴 철회 여부
- 회원 정보를 보관하고 있을 기간

**Comment by IDKNWHORU** [comment]
사용자 데이터를 지워야 될 경우 아래 의존 관계를 파악해서 데이터를 모두 지워야 됨.

![Image](https://github.com/Ludium-Official/ludium-world/assets/49608580/6ac7b2d6-64a4-45ca-baa8-3dcfc6c79549)

**Comment by IDKNWHORU** [comment]
### 회원 탈퇴 버튼
![Image](https://github.com/Ludium-Official/ludium-world/assets/49608580/8561e959-b6dd-4549-8ce5-01a42b377e34)
### 회원 탈퇴 페이지
![Image](https://github.com/Ludium-Official/ludium-world/assets/49608580/f838890f-d000-45db-a9fc-f972fc143966)

**Comment by LudiumAgwn** [comment]
1. 각 종 사이버머니, 캐쉬, 마일리지, 포인트 등의 삭제
- 현재 다루고 있지 않음

2. 이메일과 연계된 모든 사적인 영역의 정보와 게시물 삭제
- 게시물은 삭제되지 않음. 닉네임을 "탈퇴한 회원"으로 일괄 변경

3. 환불 수수료 부과, 소액 잔액의 미환급
- 미적용

4. 일정기간 동안 재가입 불가 및 동일 아이디 사용 가능 여부
- 재가입 가능. 재가입시 새로운 아이디 생성 과정으로 연동

5. 회원탈퇴 이후에도 개인정보 보유하는 경우, 그 근거와 사유 및 기간에 관한 사항
- 구글 ID, 닉네임, 자기 소개를 비롯한 개인 정보는 보유하지 않음. 게시글은 "탈퇴한 회원" 형태로 저장

6. 기타 해당 웹사이트의 정책, 약관 등에서 정하고 있는 정보 삭제
- 개인 정보와 관련된 모든 정보 삭제

추가 필요 사안
1. 개인 정보 정책 문서 작성 및 Footer 연동
2. 이용약관 문서 작성 및 Footer 연동

**Comment by IDKNWHORU** [comment]
@LudiumAgwn 
회원 탈퇴 페이지 + 회원 탈퇴 버튼은 디자인 작업이 필요함

**Comment by IDKNWHORU** [comment]
### 회원 탈퇴 약관
본 약관은 회원님이 루디움의 회원 탈퇴를 신청할 경우 적용되는 조건과 절차에 대해 설명합니다. 탈퇴 절차를 진행하기 전에 아래의 내용을 주의 깊게 읽어주시기 바랍니다.

1. 정보 및 게시물 삭제
회원 탈퇴 시, 이메일과 연계된 모든 사적인 영역의 정보 및 개인적인 게시물은 삭제됩니다. 단, 기존에 작성하신 게시물은 삭제되지 않으며, 작성자 명은 "탈퇴한 회원"으로 일괄 변경됩니다. 이는 커뮤니티 내의 정보 연속성을 유지하기 위함입니다.
2. 재가입 정책
회원 탈퇴 후, 재가입을 희망하실 경우 가능합니다. 다만, 재가입 시 새로운 아이디를 생성하는 과정을 거쳐야 하며, 이전 아이디로의 복구는 불가능합니다.
3. 개인정보 보유 및 삭제
회원 탈퇴 시, 구글 ID, 닉네임, 자기소개를 비롯한 개인 정보는 모두 삭제됩니다. 단, 특정 게시글은 "탈퇴한 회원" 형태로 남게 되며, 이는 커뮤니티의 토론 및 정보 공유의 연속성을 위해 필요한 최소한의 조치입니다.
4. 기타 정보 삭제
탈퇴 과정에서 회원님의 개인 정보와 관련된 모든 데이터는 루디움의 데이터베이스에서 삭제됩니다. 이는 개인정보 보호 및 데이터 보안을 위한 조치입니다.
5. 주의 사항
탈퇴 후, 이전에 이용하셨던 이메일로는 동일한 아이디로 재가입이 불가능합니다. 재가입을 원하실 경우, 새로운 아이디 생성이 필요합니다.
회원 탈퇴를 신청하시기 전에, 보유하신 모든 데이터와 정보를 확인하시기 바랍니다. 탈퇴 절차 완료 후, 복구는 불가능합니다.
본 약관에 동의하실 경우, 아래의 [탈퇴 신청] 버튼을 클릭하여 탈퇴 절차를 진행해주시기 바랍니다. 탈퇴 과정에 대해 궁금한 점이 있으시다면, 언제든지 고객 지원 서비스를 통해 문의하실 수 있습니다.

이 약관은 루디움의 정책과 데이터 관리 방침에 따라 작성되었습니다. 회원님의 권리 보호와 정보의 안전한 관리를 위해 최선을 다하고 있음을 알려드립니다.

**Comment by IDKNWHORU** [comment]
@LudiumAgwn 회원 탈퇴 하는 방법에 대해 작성했어

아래 참고 자료를 확인해서, 기능 검증 해줘!

### 참고 자료
https://ludium.world/community/9b2e3e98-dd03-443f-abbf-756a80ae54a1
