### ISSUE TITLE
SEO 작업

### ISSUE THREAD

**Issue by IDKNWHORU** [Ludium-Official/ludium-world#24]
네이버 검색 엔진 최적화

**Comment by Ludiumdokjong** [comment]
구글 검색 엔진 최적화 포함

네이버 서치어드바이저
구글 서치콘솔

**Comment by IDKNWHORU** [comment]
네이버 웹 마스터 가이드: https://searchadvisor.naver.com/guide/seo-basic-intro

**Comment by IDKNWHORU** [comment]
검색엔진 최적화 작업 대상
- 스키마 마크업(JSON-LD)

**Comment by IDKNWHORU** [comment]
구글 서치 콘솔 인사이트(루디움)
https://search.google.com/search-console/insights?resource_id=https%3A%2F%2Fludium.world%2F&hl=ko

**Comment by IDKNWHORU** [comment]
네이버, 구글 검색 엔진에 노출되는것을 확인함
