### ISSUE TITLE
니어 지갑 연결

### ISSUE THREAD

**Issue by IDKNWHORU** [Ludium-Official/ludium-world#49]
프로필 페이지에서 니어 지갑을 설정할 수 있는 화면 추가

**Comment by IDKNWHORU** [comment]
@LudiumAgwn 지갑 연결하는거 my near wallet만 지원하게 해도 될까? 그리고 지갑 연결 한 번 하면 다른 브라우저나 컴퓨터에서도 연동되서 자동 지갑연결 해달라고 하는걸 요청하는거 맞지?

**Comment by IDKNWHORU** [comment]
@LudiumAgwn 지갑 연결하는거 my near wallet만 지원하게 해도 될까? 그리고 지갑 연결 한 번 하면 다른 브라우저나 컴퓨터에서도 연동되서 자동 지갑연결 해달라고 하는걸 요청하는거 맞지?

**Comment by LudiumAgwn** [comment]
어차피 확장성을 생각하면 Wallet Selector 같은 걸로 연결하는게 나을 것 같아. 그리고 자동 지갑 연결 맞음!

https://docs.near.org/tools/wallet-selector

**Comment by ludiumbasky** [comment]
우선은 마이니어월렛만 연결하는 걸로 하고 
다른 요구나 요청이 있을 시에 추가하는 걸로 하자

**Comment by ludiumbasky** [comment]
https://github.com/Ludium-Official/ludium-world/issues/57#issuecomment-2141161310

연결 기능 확인
