### ISSUE TITLE
기존 프로필 수정 버튼 위치 변경

### ISSUE THREAD

**Issue by IDKNWHORU** [Ludium-Official/ludium-world#57]
#56 보상지급 관련 화면 기획서 프로필 페이지 참고

![image](https://github.com/Ludium-Official/ludium-world/assets/49608580/f7cf3cb9-15a1-47c1-8635-ee767e02b05c)

**Comment by IDKNWHORU** [comment]
아래 이슈는 중복되므로 완료 처리함
- #58
- #59
- #60

**Comment by IDKNWHORU** [comment]
@ludiumbasky
https://my-near-wallet-test.ludium.world/ 에서 원하는 기능이 되는지 확인한 다음에 결과 알려줘!

**Comment by ludiumbasky** [comment]
![연결](https://github.com/Ludium-Official/ludium-world/assets/151835493/a13f858e-bdd8-4d73-a304-7eb275368b37)

버튼 위치 변경, 지갑연결 확인

**Comment by IDKNWHORU** [comment]
기능 확인 되었으므로 https://my-near-wallet-test.ludium.world/ 홈페이지는 이제 삭제함
