### ISSUE TITLE
요청 완료 페이지

### ISSUE THREAD

**Issue by IDKNWHORU** [Ludium-Official/ludium-world#62]
#56 보상지급 관련 화면 기획서 요청 완료, 레퍼런스 페이지 참고

![image](https://github.com/Ludium-Official/ludium-world/assets/49608580/698fdb72-ae7d-40e0-a114-a32536939a11)

![image](https://github.com/Ludium-Official/ludium-world/assets/49608580/4b2e1542-98bf-41e5-82a2-d7f92e9c5fdf)

**Comment by loosie** [comment]
Payment 시스템 API  
- https://github.com/Ludium-Official/ludium-world/issues/55

**Comment by IDKNWHORU** [comment]
이 페이지는 폐기됨
