### ISSUE TITLE
[문의] 디스코드 채널에 깃헙 봇 적용하는 방법

### ISSUE THREAD

**Issue by LudiumAgwn** [Ludium-Official/ludium-world#63]
현재 루디움 디스코드 채널에서 볼 수 있는 깃헙 이슈 알림봇 설정 방법이 설명되 자료 같은게 있을까? 로글스 자료 제작도 이슈로 로그 남기는 중인데 액티비티를 바로 디코에서 알림으로 확인할 수 있도록 조처하는 걸 고려 중이라서 물어봄!

**Comment by IDKNWHORU** [comment]
아래글을 참고해봐!

https://velog.io/@hellojihyoung/Git-Github%EA%B3%BC-Discord-Webhook-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0

**Comment by LudiumAgwn** [comment]
<img width="996" alt="스크린샷 2024-06-03 오후 8 37 18" src="https://github.com/Ludium-Official/ludium-world/assets/125532594/114b1c46-f242-41fa-b834-31b0d0d122db">

로드 투 방콕 / 두바이 리포의 웹훅을 디스코드에 연결한 것 같은데 안 뜨는 이유가 뭘까?

**Comment by IDKNWHORU** [comment]
@LudiumAgwn 
이따 설정 어떻게 했는지 봐줄게!

**Comment by IDKNWHORU** [comment]
@LudiumAgwn 
설정 어떻게 되어있는지 봐줄 수 있음. 평일에 9~19시는 대응이 안된다고 보면되고, 13~14시는 조금 도와줄 수 있음!
그리고 테스트 서버 설정하는데 도움이 필요해! 사무실 언제 갈것 같은지 알려줘.

**Comment by LudiumAgwn** [comment]
> @LudiumAgwn 설정 어떻게 되어있는지 봐줄 수 있음. 평일에 9 ~ 19시는 대응이 안된다고 보면되고, 13 ~ 14시는 조금 도와줄 수 있음! 그리고 테스트 서버 설정하는데 도움이 필요해! 사무실 언제 갈것 같은지 알려줘.

사무실 도차쿠

**Comment by IDKNWHORU** [comment]
오우.. 미팅 끝나면 알려줘
