### ISSUE TITLE
미션 수정 페이지에 지급할 보상을 설정하는 기능 추가

### ISSUE THREAD

**Issue by IDKNWHORU** [Ludium-Official/ludium-world#66]
## 화면 기획서
![image](https://github.com/Ludium-Official/ludium-world/assets/49608580/eef55324-6c06-400b-9922-d4c811c563e2)

## 유저 플로우
![image](https://github.com/Ludium-Official/ludium-world/assets/49608580/b74972fc-2b45-4d2f-8a03-3320a2670fef)

### 참고
- #56 참고

**Comment by loosie** [comment]
해당 API 작업해서 올려놨어! response 상세 정보는 [/api/coin-networks 노션 문서](https://spiral-banana-6f7.notion.site/API-076cc5eebab34f0b8bfd9061057e22eb#:~:text=GET%20/api/coin%2Dnetworks%20%20%EC%BD%94%EC%9D%B8%20%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%20%EB%AA%A9%EB%A1%9D%20%EC%A1%B0%ED%9A%8C%20%20(DONE)) 참고해줘
 
<img width="500" alt="스크린샷 2024-06-03 오후 7 28 56" src="https://github.com/Ludium-Official/ludium-world/assets/54282927/07f48a89-444c-4401-a66d-a2b48751c25e">

**Comment by IDKNWHORU** [comment]
@ludiumbasky https://test.ludium.world 에서 테스트 해보고 결과 알려줘!

**Comment by ludiumbasky** [comment]
우선 권한 관련해서
프로필 눌러봤더니 회원가입을 하라 그래서 '회원가입 하러 가기' 눌렀더니 메인페이지로 이동하네

아무튼 아곤 계정으로 확인한 바는
미션 수정 페이지에서 토큰 종류와 금액을 설정할 수 있는 걸 확인함

**Comment by IDKNWHORU** [comment]
@ludiumbasky 테스트 사이트에서 로그인 제대로 안되는 부분 수정해봤는데, 증상 똑같은지 알려줘!
