### ISSUE TITLE
나의 보상 페이지 추가

### ISSUE THREAD

**Issue by IDKNWHORU** [Ludium-Official/ludium-world#67]
## 화면 기획서
![image](https://github.com/Ludium-Official/ludium-world/assets/49608580/a3d0174a-0510-430c-a022-875ae1b085e0)

## 유저 플로우
![image](https://github.com/Ludium-Official/ludium-world/assets/49608580/5f7078e3-cbc4-41a2-9b55-dde8735ce115)

### 참고
- #56

**Comment by loosie** [comment]
해당 API는 일단 작업해놨는데 미션이랑 같이 한번에 쿼리해도 될거야 [/api/me/reward-claims 노션 문서](https://spiral-banana-6f7.notion.site/API-076cc5eebab34f0b8bfd9061057e22eb#:~:text=GET%20/api/me/reward%2Dclaims%20%EC%9D%B8%EC%A6%9D%EB%90%9C%20%EC%82%AC%EC%9A%A9%EC%9E%90%EC%9D%98%20%EC%9E%90%EC%8B%A0%20%EB%B3%B4%EC%83%81%20%EB%82%B4%EC%97%AD%20%EC%A1%B0%ED%9A%8C%20(WIP)) response 데이터 형태 한번 참고해줘

**Comment by IDKNWHORU** [comment]
@ludiumbasky 나의 보상 페이지에서 제목 클릭하면 어떻게 되어야해? 이동 버튼눌렀을 때만 블록 스캔 페이지로 이동하면 되는건가?

**Comment by IDKNWHORU** [comment]
@ludiumbasky 보상 요청, 나의 보상 조회되는지 확인 부탁해!
