### ISSUE TITLE
나의 작업 페이지에 보상 요청 기능 추가

### ISSUE THREAD

**Issue by IDKNWHORU** [Ludium-Official/ludium-world#80]
![image](https://github.com/Ludium-Official/ludium-world/assets/49608580/61dd1e57-929f-4785-a60e-8a2deba51b6d)

- https://github.com/Ludium-Official/ludium-world/issues/56#issuecomment-2167753063 의 [보상지급 관련 화면 기획서(24.06.14).pdf](https://github.com/user-attachments/files/15836856/24.06.14.pdf) 참고

**Comment by IDKNWHORU** [comment]
@loosie ludium에서 작업도 보상 요청해달라고해서 추가 기능을 개발해야 될거 같아!

**Comment by IDKNWHORU** [comment]
@loosie 작업 테이블은 `detailed_posting` 테이블을 참고해봐!

**Comment by loosie** [comment]
고마워! 우선 로드맵에 작업 등록해놨어! 이번주는 바빠서 힘들고 다음주중에 확인해서 작업해볼게!

**Comment by loosie** [comment]
@IDKNWHORU 작업 보상 요청 기능도 추가했어. api를 새롭게 추가한 것은 없고 기존 POST /api/reward-claims의 req body를 바꿔줬어
as-is) 
```
{
  "amount": "string",
  "coin_network_id": "string",
  "mission_id": "string",
  "user_address": "string"
}
```
to-be) 
```
{
  "amount": "string",
  "coin_network_id": "string",
  "resource_id": "string",
  "resource_type": "MISSION | DETAILED_POSTING",
  "user_address": "string"
}
```

이에 따라서 reward-claims 조회해오는 response도 수정되었어!
- mission_id -> resource_id, resource_type

자세한 건 swagger에도 반영되었으니 확인 가능해! (`{ludium_payment_domain}/swagger-ui`로 접속 가능해!)

**Comment by IDKNWHORU** [comment]
@loosie detailed_posting테이블에 update_at컬럼 없어서 에러난다고 하는데, update_at 컬럼 추가하면 되니?

![image](https://github.com/user-attachments/assets/35b58487-8dbb-498a-a719-0cca365c679a)

**Comment by loosie** [comment]
@IDKNWHORU 아 그렇네...! 넣는게 좋긴할 거 같은데 사용 예정이 없으면 내가 뺄게!

**Comment by IDKNWHORU** [comment]
@loosie 나중에 사용할 일이 있을거 같으니 넣어둘게! 다음부터는 기존에 있는 스키마랑 맞춰줘.

**Comment by loosie** [comment]
오키용! 잘 체크했어야했는데ㅎㅎ... 고마워!

**Comment by IDKNWHORU** [comment]
@loosie 보상 요청 실패했을 때 재요청 보내는건 다른 방법이 있니? 보상 요청 실패하고나서 다시 보상 요청을 보내도 409 에러코드를 반환하는거 같아.

![image](https://github.com/user-attachments/assets/d034bcc2-0634-4a93-b239-49476f0bf704)
![image](https://github.com/user-attachments/assets/f7b0f5e7-e01a-4c1f-818a-aab6546c9712)
![image](https://github.com/user-attachments/assets/d95f938f-3355-4a40-84a5-104658ce4c0b)

**Comment by loosie** [comment]
@IDKNWHORU 아 요거 로직 일부분 업데이트해줘야겠다 코드 변경하고 다시 알려줄게!

**Comment by IDKNWHORU** [comment]
@loosie 결제 테스트 서버 최신 코드로 배포되어있을까?

**Comment by loosie** [comment]
@IDKNWHORU 응응 배포는 해놨는데 DB 커넥션 풀 오류가 떠있네 설정들 좀 업데이트하고 보완한 다음에 다시 알려줄게!

**Comment by loosie** [comment]
@IDKNWHORU 우선 재시도 부분 수정해서 올려서 배포했으니 시간될 때 확인부탁해~

**Comment by IDKNWHORU** [comment]
@ludiumbasky 기능 추가했으니까 테스트해줘!

![image](https://github.com/user-attachments/assets/b8a0afd9-1b0e-46f2-b8fa-6df4170bf4df)
![image](https://github.com/user-attachments/assets/5ecf0cda-db3d-48ee-a3ca-6d105860bba8)
