### ISSUE TITLE
‘나의 미션 페이지’, ‘나의 보상 페이지’ 에서 ‘승인됨’, 혹은 ‘요청 완료’ 보다 좀 더 명확한 단어를 사용

### ISSUE THREAD

**Issue by IDKNWHORU** [Ludium-Official/ludium-world#84]
요청완료 → 지급 완료
![image](https://github.com/user-attachments/assets/ba8b9490-856f-45a5-a554-5ecb61b15328)

_Originally posted by @IDKNWHORU in https://github.com/Ludium-Official/ludium-world/issues/83#issuecomment-2253809138_

**Comment by IDKNWHORU** [comment]
![image](https://github.com/user-attachments/assets/3e51c7b7-ebde-497b-a502-0cdaa452397a)

**Comment by IDKNWHORU** [comment]
@ludiumbasky 테스트 확인해줘

**Comment by ludiumbasky** [comment]
확인완료
