### ISSUE TITLE
미션 업로드 서버 사이드 에러

### ISSUE THREAD

**Issue by LudiumAgwn** [Ludium-Official/ludium-world#87]
<img width="1438" alt="스크린샷 2024-07-30 오전 9 25 22" src="https://github.com/user-attachments/assets/a7d8cdde-4d07-4f09-9711-1c432b8e3cce">

**Comment by IDKNWHORU** [comment]
미션 생성자와 미션 수정자의 계정이 일치하지 않는 문제임. 에러 메시지는 버그이므로 니어 지갑 배포 패치할 때 같이 반영될 것
