### ISSUE TITLE
페이지 에러

### ISSUE THREAD

**Issue by LudiumAgwn** [Ludium-Official/ludium-world#90]
1. imagebb 에러
<img width="1433" alt="스크린샷 2024-08-02 오후 3 23 32" src="https://github.com/user-attachments/assets/fb0728d2-ec6c-4311-a102-d135290942bd">

2. 아티클 업로드 에러
<img width="1440" alt="스크린샷 2024-08-02 오후 3 49 21" src="https://github.com/user-attachments/assets/b9509251-39a2-442d-b754-64341b472b09">

**Comment by LudiumAgwn** [comment]
2번 문제는 다른 아이디로 접속했을 때 가능한 것 확인. 최초 제작자가 아곤 아이디였던 걸로 기억하는데 왜 바뀌었는지는 모르겠음. 어찌됐든 그런걸로

**Comment by IDKNWHORU** [comment]
@LudiumAgwn 그거 처음 올린사람 독종임

**Comment by IDKNWHORU** [comment]
@LudiumAgwn 
- [ ] imgbb 에러는 좀 살펴봐야 될거 같아.
- [X] 미션, 아티클 같은 학습 자료는 관리자 권한 가지고 있으면 수정할 수 있게 변경함
