### ISSUE TITLE
공고 작성 과정에서의 서버 사이드 에러

### ISSUE THREAD

**Issue by LudiumAgwn** [Ludium-Official/ludium-world#99]
에러 발생 지점: 공고 관리 -> NEAR AI-PGF 그랜츠 -> 작업 목록(제목 입력)
<img width="1438" alt="스크린샷 2024-08-14 오전 9 42 25" src="https://github.com/user-attachments/assets/a7b0ec45-c02d-4400-9bd1-50988159afdc">

지원서 양식 작성은 완료

**Comment by IDKNWHORU** [comment]
@loosie payment 서버 접속 에러가 발생하는거 같아!

![image](https://github.com/user-attachments/assets/119ce887-ad1b-4caf-9539-b2e3786f5a2c)

**Comment by IDKNWHORU** [comment]
@loosie payment url로 요청했을 때 523 에러가 발생하는데, 내가 해줘야 될게 있을까?

![image](https://github.com/user-attachments/assets/7d84ba8e-c324-43aa-9dc7-62e832ecc416)

**Comment by loosie** [comment]
@IDKNWHORU 이건 cloudflare 관련 인증 문제인 것 같은데 내 로컬에서도 페이먼트 서버로 접속이 안되네

**Comment by IDKNWHORU** [comment]
8443 포트로 포워딩 해놓은게 문제일 수도 있겠다. 금요일에 페이먼트 서버는 살롱으로 옮겨봐야겠어.

**Comment by IDKNWHORU** [comment]
@LudiumAgwn 내일까지 보상 설정 API 조회 못해도 페이지는 불러올 수 있도록 수정할게

**Comment by IDKNWHORU** [comment]
@LudiumAgwn 보상 설정은 못하지만 작업, 미션은 수정할 수 있게 수정함
